# when finished move to ./server/meta-data
#cloud-config
autoinstall:
  version: 1
  refresh-installer:  # start with an up-to-date installer
  update: yes
  interactive-sections:  # Install groups listed here will wait for user input
    - storage
  storage:  # should set the interactive default but doesn't seem to work??
    layout:
      name: lvm
      match:
        size: largest
  locale: en_US.UTF-8
  keyboard:
    layout: us
  identity:  # This is section you may want to add to interactive-sections  (default user is WOSland and default password is $$WOSland001)
    hostname: WOSland-Server
    password: "$6$R0qcy1SNjQqIND5z$qc20Ip1fQQWj2nS5LpZEydH43f0JpetEwozbHVKd1qnFuOhUuHKn.HFVTZFCWhIoyoJnzPigKkbUE.kmruHUJ/"
    username: WOSland
  ssh:
    allow-pw: true
    install-server: true
  apt:
    sources:
      ignored1:  # This is here to get the yaml formatting right when adding a ppa
        source: ppa:graphics-drivers/ppa
        source: ppa:deadsnakes/ppa
  packages: 
    - build-essential
    - network-manager
    - dkms
    - emacs-nox
    - ubuntu-desktop-minimal
    - git
    - wget
    - python3-full
    - python3-is-python
    - software-properties-common
  package_update: true
  package_upgrade: true
  late-commands:
    # Changing from networkd to NetworkManager
    # move existing config out of the way
    - find /target/etc/netplan/ -name "*.yaml" -exec sh -c 'mv "$1" "$1-orig"' _ {} \;
    # Create a new netplan and enable it
    - |
      cat <<EOF | sudo tee /target/etc/netplan/01-netcfg.yaml
      network:
        version: 2
        renderer: NetworkManager
      EOF
    - curtin in-target --target /target netplan generate
    - curtin in-target --target /target netplan apply
    - curtin in-target --target /target systemctl enable NetworkManager.service
    # Write a script that can take care of some post install setup "late-commands" cannot be interactive unfortunately"
    - |
      cat <<EOF | sudo tee /target/etc/finish-install-setup.sh
      #!/usr/bin/env bash
      echo *************************
      echo ****  Finish Setup   ****
      echo ************************* 
      echo 'Enter the hostname for this system: '
      read NEW_HOSTNAME
      hostnamectl set-hostname \${NEW_HOSTNAME}
      echo
      echo 'Enter the timezone for this system: '
      echo 'America/Los_Angeles America/Denver Europe/Amsterdam Europe/Berlin Asia/Tokyo'
      read NEW_TIMEZONE
      timedatectl set-timezone \${NEW_TIMEZONE}
      echo
      echo 'Put in your discord bot token'
      echo 'in case no token is give now you have to change it later'
      read bot_token
      echo
      echo ${bot_token} >> /home/WOSland/bot/bot_token.txt
      echo 
      echo *************************
      echo
      echo *************************
      echo 'Restarting to finish ...'
      shutdown -r 3
      EOF
    - curtin in-target --target /target chmod 744 /etc/finish-install-setup.sh
    - ls -l > /target/root/ls.out
    - pwd > /target/root/pwd.out
    - mount > /target/root/mount.out
    - touch afile
    - cp afile /target/root/
    - ls -l / > /target/root/ls-root.out
    - ls -l /target > /target/root/ls-target.out
    - ls -l /target/cdrom > /target/root/ls-target-cdrom.out
    - curl -o main.py https://raw.githubusercontent.com/whiteout-project/bot/main/main.py
    - curl -o requirements.txt https://raw.githubusercontent.com/whiteout-project/bot/main/requirements.txt
    - mkdir /target/home/WOSland/bot
    - touch /target/home/WOSland/bot/bot_token.txt
    - cp main.py /target/home/WOSland/bot/main.py
    - cp requirements.txt /target/home/WOSland/bot/requirements.txt
  user-data: # Commands here run during first boot (cannot be interactive)
    runcmd:
      - cd /home/WOSland/bot
      - python3 -m venv venv
      - cd /home/WOSland/Pictures/
      - wget https://raw.github.com/ikketim/install/main/woslandOS/source/woslandOS.png
      - gsettings set org.gnome.desktop.background picture-uri file:///home/WOSland/Pictures/woslandOS.png
      - gsettings set org.gnome.desktop.background picture-uri-dark file:///home/WOSland/Pictures/woslandOS.png
      - curl -o /etc/systemd/system/wosbot.service https://raw.github.com/ikketim/install/main/woslandOS/source/wosbot.service
      - systemctl daemon-reexec
      - systemctl daemon-reload
      - systemctl enable wosbot.service
      - |
        #!/usr/bin/env bash
        echo ''
        echo '***************************************'
        echo ' To complete install setup please run, '
        echo ' sudo /etc/finish-install-setup.sh'
        echo
        echo ' the account password and sudo password is: $$WOSland001 '
        echo ' you can change this password with the command passwd '
        echo '***************************************'
        echo ''
